### ISSUE TITLE
Scroll issues in mobile

### ISSUE THREAD

**Issue by norman784** [mint-lang/mint-website-rails#67]
In the Learn section you cannot scroll the Pages menu.

**Comment by surrealist** [comment]
Yes. I found this problem too. So it has difficulties and impossible to navigate whole of the left sidebar menu.

I'd tested it with Edge, Chrome, and Safari on iPhone X.

![image](https://user-images.githubusercontent.com/344784/114261150-43eb3700-9a03-11eb-8b77-74a34d5c7e52.png)

**Comment by raoulduke** [comment]
Hey all, this fix has caused an issue on a couple pages of the guide on desktop (see "Tools", "The Main Component", "Styling with CSS" pages for example). When the sidebar is longer than the main content the footer overlaps the sidebar because the `toc__wrapper` is fixed to `height: 100vh;` and doesn't allow the content to dynamically push down the footer. If you remove this restriction it fixes the issue, but I'm not sure what effect that will have with the Safari issue.
